FROM nginx
RUN apt-get update && apt-get -y install  keepalived net-tools procps rsyslog kmod ipvsadm
COPY keepalived.conf /etc/keepalived/keepalived.conf
COPY nginx.conf /etc/nginx/nginx.conf
COPY check_nginx.sh /etc/keepalived/nginx_check.sh
RUN chmod 644 /etc/keepalived/keepalived.conf




