[package]
name = "actixwebdemo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.3.3"
actix-rt = "1.1.1"
log = "0.4.15"
env_logger = "0.9.0"
futures = "0.3.24"